# Allow clients to connect without a username or password.
allow_anonymous true

# Listen for connections on the standard MQTT port inside the container.
listener 1883

# Define where to store persistent data inside the container.
persistence true
persistence_location /mosquitto/data/
